import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { getUserFromCookies } from "@/helper/helper";
import NewUserContext from "@/components/contexts/userContext";
export const metadata: Metadata = {
  title: "MART",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookies();
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <NewUserContext user={user}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster richColors />
            {children}
          </ThemeProvider>
        </NewUserContext>
      </body>
    </html>
  );
}
